# REQUIRED CHANGES
# Edit next line to provide your own name.
title: Cortez Mosley | Professional Portfolio
# Edit next line, replacing 'techfolios' with your github username
url: "https://cmosley757.github.io"
# Edit next line so that baseurl is "" if your repo is <username>.github.io
baseurl: ""

# OPTIONAL CHANGES
## Specify the theme using any of the css files in css/techfolio-theme
techfolio-theme: default.css
## Specify the formatting for triple backquote code sections.
bio-page-title: Resume

bio-theme: bio/resume.html
# Specify the code highlight theme using any of the css files in css/rouge
rouge-theme: github.css
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
strict_front_matter: true
mathjax: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
include:
  - .nojekyll
  - _data
plugins:
  - jekyll-gist
